application:
  env: local
  debug: true

handler:
  context-timeout: 3s

token:
  access_ttl: 5h
  refresh_ttl: 8760h

server:
  write-timeout: 3s
  read-timeout: 3s
  port: 8092
  host: localhost

auth:
  host: http://localhost
  port: 8091
  timeout: 3s
